version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456cdut
      MYSQL_DATABASE: partner_vote_db
    ports:
      - "3306:3306"
    volumes:
      - /opt/app/mysql:/var/lib/mysql
    networks:
      - app-network

  redis-cache:
    image: redis:7.0
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  springboot-app:
    image: eclipse-temurin:17
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /opt/app/app.jar:/app.jar
    command: java -Xms256m -Xmx512m -jar /app.jar
    environment:
      VOTING_DATASOURCE_HOST: mysql-db
      VOTING_DATASOURCE_PORT: 3306
      VOTING_DATASOURCE_DATABASE: partner_vote_db
      VOTING_DATASOURCE_USERNAME: root
      VOTING_DATASOURCE_PASSWORD: 123456cdut
      VOTING_REDIS_HOST: redis-cache
      VOTING_REDIS_PORT: 6379
    networks:
      - app-network
    depends_on:
      - mysql-db
      - redis-cache

networks:
  app-network:
    driver: bridge
