voting:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: partner_vote_db
    username: root
    password: 123456
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: wx439e92e6e8fc24df
    secret: a15f0a7e1fc919371ebc4a3492bbe324

