voting:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: mysql-db
    port: 3306
    database: partner_vote_db
    username: root
    password: 123456
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: mysql-db
    port: 6379
    password:
    database: 0
  wechat:
    appid:
    secret:

